/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import java.awt.GridLayout;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ESTUDIANTES
 */
public class FrmMatrizDiagonal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMatrizDiagonal.class.getName());

    /**
     * Creates new form FrmEmergente
     */
    
    private int n;
    private JTextField[][] txtDigit;
    
    public FrmMatrizDiagonal() {
        initComponents();
        
        btnImprimir.addActionListener(evt -> imprimirDiagonales());
    }
    
    public void setTamaño(int n) {
        this.n = n;
        crearMatriz();
    }
    
    public void crearMatriz(){
        pnlMatriz.removeAll();
        pnlMatriz.setLayout(new GridLayout(n,n,5,5));
        
        txtDigit = new JTextField[n][n];
        
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                txtDigit[i][j] = new JTextField(3);
                pnlMatriz.add(txtDigit[i][j]);
            }
        }
        
        pnlMatriz.revalidate();
        pnlMatriz.repaint();
        
        int size = Math.min(600, n*50);
        setSize(size, size + 70);
        setLocationRelativeTo(null);
        
        
    }
    
    private void imprimirDiagonales(){
        int[][] matriz = new int[n][n];
        
        try{
            for (int i = 0; i < n; i++){
                for (int j = 0; j < n; j++) {
                    matriz[i][j] = Integer.parseInt(txtDigit[i][j].getText());
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese solo números enteros en la matriz.");
            return;
        }
        StringBuilder sb = new StringBuilder("Diagonal Principal: ");
        for (int i = 0; i < n; i++) {
            sb.append(matriz[i][i]).append(" ");
        }

        sb.append("\nDiagonal Secundaria: ");
        for (int i = 0; i < n; i++) {
            sb.append(matriz[i][n - 1 - i]).append(" ");
        }

        JOptionPane.showMessageDialog(this, sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlMatriz = new javax.swing.JPanel();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        Panel.setToolTipText("");
        Panel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("MATRIZ DIAGONAL");
        Panel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        pnlMatriz.setLayout(new java.awt.GridBagLayout());
        Panel.add(pnlMatriz, java.awt.BorderLayout.CENTER);

        btnImprimir.setText("Imprimir ");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        Panel.add(btnImprimir, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(Panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMatrizDiagonal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlMatriz;
    // End of variables declaration//GEN-END:variables
}
